@startuml http

skinparam ParticipantPadding 100
skinparam BoxPadding 10

participant "Client" as client #BUSINESS
participant "Server" as server #BUSINESS

autonumber "0."

client -> server : [SYN] seq=0
activate client #F5DDAD
activate server #F5DDAD

server -> client : [SYN, ACK] seq=0, ack=1

client -> server : [ACK] seq=1, ack=1
deactivate client
deactivate server

client -> server : [PSH, ACK] seq=1, ack=1, len=80
activate client #F5DDAD
activate server #F5DDAD
note right of client
    GET/ HTTP/1.1
end note

server -> client : [ACK] seq=1, ack=81
deactivate client
deactivate server

client -> server : [FIN, ACK] seq=81, ack=1
activate client #F5DDAD
activate server #F5DDAD

server -> client : [FIN, ACK] seq=1, ack=82

client -> server : [ACK] seq=82, ack=2
deactivate client
deactivate server

@enduml