version: '3.7'

services: 

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports: 
      - 2181:2181
    volumes: 
      - ./data/zookeeper:/data

  kafka1:
    container_name: kafka1
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment: 
      HOSTNAME_COMMAND: "hostname -i |awk '{print $$1}'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "test1:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/opt/kafka/data"
    depends_on: 
      - zookeeper
    volumes: 
      - ./data/kafka-9092:/kafka

  # kafka2:
  #   container_name: kafka2
  #   image: wurstmeister/kafka
  #   ports:
  #       - 9093:9092
  #   environment: 
  #     HOSTNAME_COMMAND: "hostname -i |awk '{print $$1}'"
  #     KAFKA_ADVERTISED_PORT: 9093
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_CREATE_TOPICS: "test2:1:1"
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_LOG_DIRS: "/opt/kafka/data"
  #   depends_on: 
  #     - zookeeper
  #   volumes: 
  #     - ./data/kafka-9093:/kafka

  # kafka-manager:
  #   container_name: kafka-manager
  #   image: sheepkiller/kafka-manager
  #   ports:
  #     - 9000:9000
  #   environment:
  #     ZK_HOSTS: zookeeper:2181