version: '3.7'

services: 
    zookeeper:
        image: wurstmeister/zookeeper
        ports: 
            - 2181:2181
        volumes: 
            - ./data/zookeeper:/data
    
    kafka:
        image: wurstmeister/kafka
        ports:
            - 9002:9002
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_BROKER_ID: "1"
            KAFKA_LOG_DIRS: "/opt/kafka/data"
            KAFKA_CREATE_TOPICS: "test:1:1"
        volumes: 
            - ./data/kafka:/kafka