version: '3.7'

services: 
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper
        hostname: zookeeper
        ports: 
            - 2181:2181
        volumes: 
            - ./data/zookeeper:/data

    kafka1:
        container_name: kafka1
        image: wurstmeister/kafka
        ports:
            - 9002:9002
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9002
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: 9002
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_BROKER_ID: 1
            KAFKA_LOG_DIRS: "/opt/kafka/data"
            KAFKA_CREATE_TOPICS: "test:1:1"
        depends_on: 
            - zookeeper
        volumes: 
            - ./data/kafka1:/kafka

    kafka2:
        container_name: kafka2
        image: wurstmeister/kafka
        ports:
            - 9003:9003
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9003
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: 9003
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_BROKER_ID: 2
            KAFKA_LOG_DIRS: "/opt/kafka/data"
        depends_on: 
            - zookeeper
        volumes: 
            - ./data/kafka2:/kafka

    kafka-manager:
        container_name: kafka-manager
        image: sheepkiller/kafka-manager
        ports:
            - 9000:9000
        environment:
            ZK_HOSTS: zookeeper:2181